window.AION2_DEFAULTS = {
  daily: [
    {
      id: "duty",
      label: "Duty Missions (5)",
      note: "Rewarded completions are shared per server",
      tag: "server",
      priority: "high",
    },
    {
      id: "odyle",
      label: "Spend Odyle Energy",
      note: "Keep below cap — +15 every 3h, max 560 / 840",
      tag: "character",
      priority: "high",
    },
    {
      id: "nightmare",
      label: "Nightmare attempts",
      note: "+2/day, banks up to 14",
      tag: "character",
      priority: "high",
    },
    {
      id: "shugo",
      label: "Shugo Festival keys",
      note: "3 keys/day, cap 12 / 21 with membership",
      tag: "server",
      priority: "high",
    },
    {
      id: "invasion",
      label: "Dimensional Invasion key",
      note: "1 key/day, banks up to 7",
      tag: "server",
      priority: "medium",
    },
    {
      id: "conquest",
      label: "Conquest reward count",
      note: "+1 every 8h, cap 21 — spend Odyle on cubes",
      tag: "character",
      priority: "medium",
    },
    {
      id: "transcendence",
      label: "Transcendence reward count",
      note: "+1 every 12h, cap 14",
      tag: "character",
      priority: "medium",
    },
    {
      id: "attendance",
      label: "Daily attendance",
      note: "Claim login reward",
      tag: "server",
      priority: "medium",
    },
  ],
  weekly: [
    {
      id: "raids",
      label: "Sanctuary raid attempts",
      note: "4 per raid — unused entries are lost",
      tag: "character",
      priority: "high",
    },
    {
      id: "ascension",
      label: "Ascension Trial (3)",
      note: "Save for higher IL later in the week if climbing",
      tag: "character",
      priority: "high",
    },
    {
      id: "subjugation",
      label: "Subjugation tickets (3)",
      note: "Weekly tickets do not roll over",
      tag: "character",
      priority: "high",
    },
    {
      id: "fissure",
      label: "Unknown Fissure / Daily Dungeon (14)",
      note: "Server-shared pool — ~2/day pacing",
      tag: "server",
      priority: "high",
    },
    {
      id: "exploration",
      label: "Exploration rewards",
      note: "7 per Expedition dungeon",
      tag: "character",
      priority: "high",
    },
    {
      id: "abyss-time",
      label: "Abyss time",
      note: "7 hours per layer base allowance",
      tag: "character",
      priority: "medium",
    },
    {
      id: "growth-dungeon",
      label: "Growth dungeon time",
      note: "7 hours per dungeon",
      tag: "character",
      priority: "medium",
    },
    {
      id: "battlefield",
      label: "Battlefield victory rewards (3)",
      note: "Weekly PvP victory rewards",
      tag: "character",
      priority: "medium",
    },
    {
      id: "claim-cubes",
      label: "Claim Conquest / Transcendence cubes",
      note: "Unobtained cube count is per server — weekly limit 10",
      tag: "server",
      priority: "high",
    },
    {
      id: "ludra",
      label: "Abyssal Forge: Ludra kill",
      note: "1 rewarded kill when available",
      tag: "character",
      priority: "medium",
    },
  ],
  shops: [
    {
      id: "cmd-pve",
      label: "Command Merchant — PvE scrolls (12)",
      note: "Buy before reset; can complete later. Server-shared.",
      tag: "buy",
      priority: "high",
    },
    {
      id: "cmd-pvp",
      label: "Abyss Command Merchant — PvP scrolls (20)",
      note: "Server-shared weekly quest scrolls",
      tag: "buy",
      priority: "high",
    },
    {
      id: "abyss-potential",
      label: "Abyss Trade — Potential Stone: Abyss (2)",
      note: "25k AP each — Growth tab",
      tag: "buy",
      priority: "high",
    },
    {
      id: "abyss-stones",
      label: "Abyss Trade — Lesser Manastones & Soulstones",
      note: "Weekly stock for gear GS",
      tag: "buy",
      priority: "medium",
    },
    {
      id: "supply-requests",
      label: "Turn in weekly supply requests",
      note: "Abyss Points and Enhance Stones",
      tag: "craft",
      priority: "medium",
    },
    {
      id: "morph-odyle",
      label: "Substance Morph — Odyle Energy",
      note: "Up to 20 on main (+4 per alt)",
      tag: "craft",
      priority: "high",
    },
    {
      id: "shugo-shop",
      label: "Shugo Festival — Soul Crystal & Radiant Odyle",
      note: "Bound materials for Soul Codex upgrades",
      tag: "buy",
      priority: "high",
    },
    {
      id: "nightmare-shop",
      label: "Nightmare shop — Soul Codex",
      note: "Feeds Soul Binding upgrades",
      tag: "buy",
      priority: "medium",
    },
    {
      id: "wind-breeze",
      label: "Wind Breeze Merchant weeklies",
      note: "Membership: Odyle, dungeon tickets, Soul Crystals",
      tag: "buy",
      priority: "medium",
    },
  ],
};
